calico:
  networkMTU: 1500
  image: calico/node:v3.10.1
  cniImage: calico/cni:v3.10.1
  enableReporting: false
  networkIpAutodetectionMethod: first-found
  ipipEnabled: true
  vxlanEnabled: false
  ipipReadiness: "- --bird-ready"
  podCIDR: 10.2.0.0/16
  networkEncapsulation: "ipipMode: Always"
